language: node_js
node_js:
  - "11"
cache: yarn
branches:
  only:
  - master

before_script:
  - yarn add @angular/cli

script:
- ng lint
- ng test --watch=false --browsers=ChromeHeadless
- ng build --prod